---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation EC2 Instance Sample Template for Service Catalog Use Case from www.ngwaabanjong.com:
  Create an Amazon EC2 instance with your chosen Amazon EC2 AMI.' 

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  Ec2AmiId:
    Description: Specific AMI ID
    Type: String
    Default: ami-03a6eaae9938c858c
  mySubnetIDs: 
    Description: Subnet IDs
    Type: 'List<AWS::EC2::Subnet::Id>'
  InstanceSecurityGroupId:
    Description: The ID of an existing security group
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Default: sg-0b52fa29523a310b5
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - m1.small
    - m1.medium
    - m1.large
    - m1.xlarge
    - m2.xlarge
    - m2.2xlarge
    - m2.4xlarge
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge
    - c1.medium
    - c1.xlarge
    - c3.large
    - c3.xlarge
    - c3.2xlarge
    - c3.4xlarge
    - c3.8xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    - g2.2xlarge
    - g2.8xlarge
    - r3.large
    - r3.xlarge
    - r3.2xlarge
    - r3.4xlarge
    - r3.8xlarge
    - i2.xlarge
    - i2.2xlarge
    - i2.4xlarge
    - i2.8xlarge
    - d2.xlarge
    - d2.2xlarge
    - d2.4xlarge
    - d2.8xlarge
    - hi1.4xlarge
    - hs1.8xlarge
    - cr1.8xlarge
    - cc2.8xlarge
    - cg1.4xlarge
    ConstraintDescription: must be a valid EC2 instance type.

#tags
  ProjectName:
    Description: Application Name
    Type: String
  Environment:
    Description: Working Env
    Type: String
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
  Region:
    Description: AWS Region
    Type: String
    Default: eus1
    AllowedValues:
      - eus1
      - eus2
  CostTags:
    Description: Application Name
    Type: String
  Version:
    Description: Version
    Type: String
    Default: "01"
  CreatedBy:
    Description: Staff ID
    Type: String
  Group:
    Description: Incharged Group
    Type: String
    Default: "Cloud Engineering"
    AllowedValues:
      - "Cloud Engineering"
      - DevOps
  projectID:
    Description: Project ID
    Type: String

# Resources
Resources:
  MyEC2Instance: 
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: !Ref Ec2AmiId  
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: !Ref InstanceSecurityGroupId
      SubnetId: !Select [0, !Ref mySubnetIDs]  # Use the first subnet ID from the list
      Tags:
        - Key: "Name"
          Value:
            Fn::Join:
            - '-'
            - - Ref: ProjectName
              - Ref: Environment
              - Ref: Region
              - "instance"
              - Ref: Version
        - Key: "CostAllocation"
          Value: !Ref CostTags
        - Key: "CreatedBy"
          Value: !Ref CreatedBy
        - Key: "Incharge Group"
          Value: !Ref Group
        - Key: "Working env"
          Value: !Ref Environment
        - Key: "Project ID"
          Value: !Ref projectID

Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value:
      Ref: MyEC2Instance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - MyEC2Instance
      - AvailabilityZone
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - MyEC2Instance
      - PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - MyEC2Instance
      - PublicIp
